# Issue Labels for Gitton
# Apply with: gh label create -f .github/labels.yml (or use GitHub API)

# Type
- name: bug
  color: "d73a4a"
  description: "Something isn't working"

- name: enhancement
  color: "a2eeef"
  description: "New feature or request"

- name: documentation
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: question
  color: "d876e3"
  description: "Further information is requested"

# Status
- name: triage
  color: "fbca04"
  description: "Needs triage"

- name: confirmed
  color: "0e8a16"
  description: "Bug confirmed or feature accepted"

- name: wontfix
  color: "ffffff"
  description: "This will not be worked on"

- name: duplicate
  color: "cfd3d7"
  description: "This issue or PR already exists"

- name: stale
  color: "ededed"
  description: "No recent activity"

# Area
- name: plugin
  color: "7057ff"
  description: "Related to plugin system"

- name: terminal
  color: "1d76db"
  description: "Related to integrated terminal"

- name: github-integration
  color: "333333"
  description: "Related to GitHub features"

- name: ai-features
  color: "ff6b6b"
  description: "Related to AI features"

- name: ui
  color: "bfd4f2"
  description: "Related to user interface"

- name: performance
  color: "e99695"
  description: "Performance improvements"

# Priority
- name: priority/high
  color: "b60205"
  description: "High priority"

- name: priority/low
  color: "c2e0c6"
  description: "Low priority"

# Special
- name: good first issue
  color: "7057ff"
  description: "Good for newcomers"

- name: help wanted
  color: "008672"
  description: "Extra attention is needed"

- name: pinned
  color: "006b75"
  description: "Pinned issue, won't be auto-closed"

- name: security
  color: "ee0701"
  description: "Security related"

- name: roadmap
  color: "5319e7"
  description: "On the roadmap"
