name: Bug Report
description: Report a bug or unexpected behavior in Gitton.
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for reporting a bug!

        Please fill out the form below to help us understand and reproduce the issue.

  - type: textarea
    id: gitton-version
    attributes:
      label: Gitton Version
      description: You can find the version in the app menu (Gitton > About Gitton).
      placeholder: e.g., 0.1.21
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      placeholder: e.g., macOS 14.0, Windows 11, Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Steps to reproduce the behavior:
      placeholder: |
        1. Open Gitton
        2. Navigate to '...'
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: |
        If applicable, paste any error logs. You can find logs in:
        - macOS: `~/Library/Logs/Gitton/`
        - Windows: `%APPDATA%\Gitton\logs\`
        - Linux: `~/.config/Gitton/logs/`
      render: shell
      placeholder: Paste error logs here...
    validations:
      required: false

  - type: textarea
    id: plugins
    attributes:
      label: Installed Plugins
      description: List any Gitton plugins you have installed when the issue occurred.
      placeholder: |
        - plugin-name-1
        - plugin-name-2
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem.
      placeholder: Additional context...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Note:** If the submit button is disabled, please check that you filled all required fields and added a **Title**.
